### ISSUE TITLE
Library Dispatch & Accelerate

### ISSUE THREAD

**Issue by francescoli** [jonathanventura/vrlt#1]
Hi Jonathan,
  I'm interested with your project vrlt. I'm working on it and try to compile a Linux executable. But I cannot find the library Dispatch and Accelerate, So I have to turn off the options in CMake. Will it lead to a better perfomance with the two libs, and where to download them?
  Regards

**Comment by jonathanventura** [comment]
Hi,
These are Mac-specific libraries, so you can't download them for other platforms.  They do increase performance on Mac.
Best,
Jonathan
