### ISSUE TITLE
Crash In FeatureMatcher

### ISSUE THREAD

**Issue by francescoli** [jonathanventura/vrlt#2]
Hi, Jonathan
   I follow the tutorial in the VillageDataset and all things go well until executing TestLocalizer. The program crash down on line 88 of featurematcher.cpp. Could you please send all the xml files generated by above steps to me? My e-mail address is 464282937@qq.com.
  Warmest regards.

**Comment by francescoli** [comment]
The above crash caused by null pointer of myfeature->descriptor. 
After fixing the bug. All the executable work, but RenderTracker dosen't show any tracking effect even when I load an obj file. I have checked locaized.xml and tracked.xml and find that the rotation and translation values of most nodes are 0.0000. Strange....

**Comment by jonathanventura** [comment]
The bug has been fixed in commit b502e7bc6e9711844bce4ee8ccb64ffe264e6032 .
